spring.application.name=api-gateway-server

server.port=8765
spring.config.import=optional:configserver:http://localhost:8888
## REGISTER WITH EUREKA SERVER
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
## MICROMETER TRACING
# Tracing
management.tracing.sampling.probability=1.0

# Resource attributes
management.opentelemetry.resource-attributes.service.name=api-gateway-server

# OTLP - Traces
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

# OTLP - Metrics
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

# OTLP - Logs
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
