spring.application.name=currency-exchange-service
#server.port=8000
server.port=0
spring.config.import=configserver:http://localhost:8888
spring.jpa.show-sql=true
# H2-CONSOLE (DATA BASE)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# EUREKA CLIENT CONFIGURATION
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
## MICROMETER TRACING
logging.level.io.opentelemetry=DEBUG
logging.level.io.micrometer=DEBUG
## Spring - BUS Rabbit MQ
spring.cloud.stream.bindings.springCloudBusInput.destination=springCloudBus
spring.cloud.stream.bindings.springCloudBusInput.group=currency-exchange-service